server: 
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    
spring:
  datasource:
    password: 
    url: jdbc:mysql://localhost/disney
    username: root 
  
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ejemplo@gmail.com
    password: password
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
jpa:
  hibernate:
    ddl-auto: create-drop
  properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQL5Dialect
     format_sql: true
  show-sql: true
  
  
    
